version: '3.8'

services:
  frontend:
    container_name: frontend
    build: 
      context: web_frontend/.
    ports:
    - "3000:3000"
  backend:
    container_name: backend
    build:
      context: node_backend/.
    env_file:
      - node_backend/.development.env
    ports:
    - "5000:5000"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - node_backend/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:

  